In [73]:
import numpy as np
import matplotlib.pyplot as plt
import random as rand

In [101]:
def TableShuffler(Table):
    #Input: Table, a 4xn_iter array
    #Output: Table Shuffled in columns (permutation)
    rng = np.random.default_rng()
    Shuffled = np.transpose(rng.permutation(np.transpose(Table)))
    return Shuffled

def TableFiltering(Table):
    #Input Table, a 4xn_iter array
    #Output: Table Filtered: Only those columns in which
    #Alice Basis = Bob Basis
    #i = 0: Alice Message
    #i = 1: Alice Basis
    #i = 2: Bob Basis
    #i = 3: Bob Measures
    SameBasisTable = np.zeros([4,1])
    for i in range(len(Table[0,:])):
        if Table[1,i] == Table[2,i]:
            newcol = np.zeros([4,1])
            for j in range(4):
                newcol[j,0]=Table[j,i]
            SameBasisTable = np.append(SameBasisTable,newcol,axis=1)
    SameBasisTable = np.delete(SameBasisTable,0,axis=1)
    return SameBasisTable

def TableGenerator(MesString,AliBasString,BobBasString,MeasString):
    #Intput: 4 arrays of 02 or 1s of same length
    #Output: Merge them into a table
    
    Table = np.zeros([4,len(MesString)])
    Table[0,:] = MesString
    Table[1,:] = AliBasString
    Table[2,:] = BobBasString
    Table[3,:] = MeasString
    
    return Table

def TableReorganization(Table,n_rep):
    #Input: Filtered Table, number of iterations for repetition code
    #Output: Reorganised table by columns in groups of n_rep
    
    newTable = Table
    columncounter = 0
                
        

In [102]:
#Trial

Message = np.random.randint(2,size = 10)
AlicBas = np.random.randint(2,size = 10)
BobBas  = np.random.randint(2,size = 10)
Measure = np.random.randint(2,size = 10)

Table = TableGenerator(Message,AlicBas,BobBas,Measure)
print(Table)
print()
Shuffled = TableShuffler(Table)
print(Shuffled)
print()
Filtered = TableFiltering(Shuffled)
print(Filtered)
print()


[[0. 0. 1. 1. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 0. 0. 1. 0.]]

[[0. 0. 0. 1. 1. 0. 0. 0. 0. 1.]
 [1. 0. 1. 0. 0. 0. 1. 0. 1. 0.]
 [1. 0. 0. 1. 0. 0. 0. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 0. 1. 1. 0.]]

[[0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [0. 1. 1. 1. 1.]]



In [70]:
zerocol = np.zeros([4,1])
onecol = np.zeros([4,1])
newcol = np.append(zerocol,onecol,axis=1)
print(newcol)

newcol = np.append(newcol,onecol,axis=1)
print(newcol)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [55]:
def 

SyntaxError: invalid syntax (<ipython-input-55-455680ca2399>, line 1)